# Generated by Django 3.2.3 on 2021-06-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0003_auto_20210620_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
