# Generated by Django 3.2.3 on 2021-06-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0005_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
