# Generated by Django 3.2.3 on 2021-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app21', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='course_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
